class ClinicalInput {
  const ClinicalInput({
    this.treated,
    this.age,
    this.sexAtBirth,
    this.postmenopausal,
    this.minimalTraumaFracture,
    this.fractureSite,
    this.egfr,
    this.frailty,
    this.lifeExpectancy,
    this.residentialCare,
    this.poorAdherence,
    this.cognitiveImpairment,
    this.dxaAvailable,
    this.dxaRecent,
    this.tScore,
    this.vitaminD,
    this.recentMajorFracture,
    this.highRisk,
    this.miOrStroke,
    this.yearsSinceMenopause,
    this.robustWoman,
  });
  final bool? treated,
      postmenopausal,
      minimalTraumaFracture,
      residentialCare,
      poorAdherence,
      cognitiveImpairment,
      dxaAvailable,
      dxaRecent,
      recentMajorFracture,
      highRisk,
      miOrStroke,
      robustWoman;
  final int? age, frailty;
  final String? sexAtBirth, fractureSite;
  final double? egfr, lifeExpectancy, tScore, vitaminD, yearsSinceMenopause;

  // retain the existing JSON rule vocabulary at this single boundary
  Map<String, Object?> toFacts() => {
    'osteoporosisTreatmentStatus': treated,
    'age': age,
    'sex': sexAtBirth,
    'postmenopausal': postmenopausal,
    'minimalTraumaFracture': minimalTraumaFracture,
    'fractureSite': fractureSite,
    'eGFR': egfr,
    'clinicalFrailtyScore': frailty,
    'lifeExpectancy': lifeExpectancy,
    'liveInResidentialCare': residentialCare,
    'knownPoorMedicationAdherence': poorAdherence,
    'cognitiveImpairment': cognitiveImpairment,
    'testAvailable': dxaAvailable,
    'testWithinLast2Years': dxaRecent,
    'T-score': tScore,
    'vitaminDLevel': vitaminD,
    'hipVertebralOrMultipleFracturesInLast24M': recentMajorFracture,
    'highRisk': highRisk,
    'historyOfMiOrStroke': miOrStroke,
    'yearSincePostmenopausal': yearsSinceMenopause,
    'isRobustWoman': robustWoman,
  };
  factory ClinicalInput.fromFacts(Map<String, dynamic> f) => ClinicalInput(
    treated: f['osteoporosisTreatmentStatus'] as bool?,
    age: (f['age'] as num?)?.toInt(),
    sexAtBirth: f['sex'] as String?,
    postmenopausal: f['postmenopausal'] as bool?,
    minimalTraumaFracture: f['minimalTraumaFracture'] as bool?,
    fractureSite: f['fractureSite'] as String?,
    egfr: (f['eGFR'] as num?)?.toDouble(),
    frailty: (f['clinicalFrailtyScore'] as num?)?.toInt(),
    lifeExpectancy: (f['lifeExpectancy'] as num?)?.toDouble(),
    residentialCare: f['liveInResidentialCare'] as bool?,
    poorAdherence: f['knownPoorMedicationAdherence'] as bool?,
    cognitiveImpairment: f['cognitiveImpairment'] as bool?,
    dxaAvailable: f['testAvailable'] as bool?,
    dxaRecent: f['testWithinLast2Years'] as bool?,
    tScore: (f['T-score'] as num?)?.toDouble(),
    vitaminD: (f['vitaminDLevel'] as num?)?.toDouble(),
    recentMajorFracture: f['hipVertebralOrMultipleFracturesInLast24M'] as bool?,
    highRisk: f['highRisk'] as bool?,
    miOrStroke: f['historyOfMiOrStroke'] as bool?,
    yearsSinceMenopause: (f['yearSincePostmenopausal'] as num?)?.toDouble(),
    robustWoman: f['isRobustWoman'] as bool?,
  );
}
