export const factSchema = {
    "eGFR": { type: "boolean" },
    "p1DemographicEligible": { type: "boolean" },
    "minimalTraumaFracture": { type: "choice", values: ["yes", "no", "not_sure"] },
    "fractureSite": { type: "choice", values: ["hip", "vertebral", "pelvis", "upper_arm", "forearm", "leg", "ribs", "hand", "foot", "face", "ankle", "not_sure"] },
    "osteoporosisTreatmentStatus": { type: "boolean" },
    "liveInResidentialCare": { type: "boolean" },
    "clinicalFrailtyScore": { type: "number" },
    "lifeExpectancy": { type: "number" },
    "knownPoorMedicationAdherence": { type: "boolean" },
    "cognitiveImpairment": { type: "boolean" },
    "testAvailability": { type: "boolean" },
    "femoralNeckTscore": { type: "number" },
    "hipTscore": { type: "number" },
    "lumbarSpineTscore": { type: "number" },
    "hipVertebralOrMultipleFracturesInLast24M": { type: "boolean" },
    "recentFractureWithin2Y": { type: "boolean" },
    "historyOf2orMoreFractures": { type: "boolean" },
    "clinicalRiskFactors": { type: "boolean" },
    "FRAX10YmajorOsteoporoticFractureRiskPercent": { type: "number" },
    "FRAX10YmajorHipFractureRiskPercent": { type: "number" },
    "antiresorptiveTreatmentStatus": { type: "boolean" },
    "antiresorptiveTreatmentOver12Months": { type: "boolean" },
    "adheredToTheTreatment": { type: "boolean" },
    "symptomaticFractureInLast12M": { type: "boolean" },
    "multipleFractures": { type: "boolean" },
    "lowBMD": { type: "boolean" },
    "priorMIorStroke": { type: "boolean" },
    "sequencingFromDenosumab": { type: "boolean" }
} as const;
