import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:csi6224_patient_feedback/data/mock_app_repository.dart';
import 'package:csi6224_patient_feedback/models/clinical_case.dart';
import 'package:csi6224_patient_feedback/models/case_investigations.dart';
import 'package:csi6224_patient_feedback/models/clinical_result_contract.dart';
import 'package:csi6224_patient_feedback/models/questionnaire.dart';
import 'package:csi6224_patient_feedback/screens/clinician_case_screen.dart';
import 'package:csi6224_patient_feedback/screens/investigations_screen.dart';
import 'package:csi6224_patient_feedback/screens/recommendation_review_screen.dart';

// Synthetic data, with pathway output generated by the unchanged TS evaluator.
class UiEvidenceRepository extends MockAppRepository {
  UiEvidenceRepository(this.fixture);
  final String fixture;
  final investigations = const CaseInvestigations(
    caseId: 'evidence-case',
    vitaminDLevel: 50,
    ionisedCalcium: 1.2,
    bodyWeightKg: 70,
    revision: 1,
    isComplete: true,
    authoritativeHypocalcaemia: false,
    hypocalcaemiaRevision: 1,
  );
  @override
  Future<ClinicalCase> fetchClinicalCase(String id) async {
    final data =
        jsonDecode(
              File(
                'test/fixtures/final_ui_evaluations.json',
              ).readAsStringSync(),
            )[fixture]
            as Map;
    return ClinicalCase.fromJson({
      'id': id,
      'patient_id': 'synthetic-patient',
      'patient_name': 'Alex Example',
      'profile_sex_at_birth': 'female',
      'status': 'evaluated',
      'revision': 1,
      'updated_at': '2026-10-09T01:00:00Z',
      'submitted_at': '2026-10-09T01:00:00Z',
      'pathway': fixture == 'p1' ? 'PATHWAY1' : 'PATHWAY2',
      'pathway_revision': 1,
      'clinician_facts': data['facts'],
      'rule_evaluation': data['evaluation'],
    });
  }

  @override
  Future<CaseInvestigations> getCaseInvestigations(String id) async =>
      investigations;
  @override
  Future<ClinicalCasePatientSummary> getClinicalCasePatientSummary(
    String id,
  ) async => ClinicalCasePatientSummary(
    caseId: id,
    patientDisplayName: 'Alex Example',
    age: 71,
    ageAsOf: DateTime(2026, 10, 9),
  );
  @override
  Future<QuestionnaireResponse?> fetchQuestionnaireResponse({
    required String patientId,
  }) async => const QuestionnaireResponse(
    id: 'synthetic-response',
    patientId: 'synthetic-patient',
    status: QuestionnaireResponseStatus.submitted,
    revision: 1,
    answers: {
      'postmenopausal': 'Yes',
      'smoking': 'Yes',
      'alcohol': 'No',
      'dairyLessThan3Serves': true,
    },
  );
  @override
  Future<ClinicalResultsReview?> getClinicalCaseResultsReview(
    String id,
  ) async => ClinicalResultsReview.fromJson(
    Map<String, dynamic>.from(
      jsonDecode(
            File('test/fixtures/dynamic_ui_advice.json').readAsStringSync(),
          )
          as Map,
    ),
  );
}

void main() {
  for (final scene in [
    'p1-review',
    'p2-review',
    'overview',
    'investigations',
  ]) {
    testWidgets('render $scene without overflow', (tester) async {
      await tester.binding.setSurfaceSize(const Size(1000, 1700));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      final font = FontLoader('EvidenceFont')
        ..addFont(
          Future.value(
            ByteData.sublistView(
              File(r'C:\Windows\Fonts\segoeui.ttf').readAsBytesSync(),
            ),
          ),
        );
      await tester.runAsync(() => font.load());
      final icons = FontLoader('MaterialIcons')
        ..addFont(
          Future.value(
            ByteData.sublistView(
              File(
                r'C:\dev\flutter\bin\cache\artifacts\material_fonts\materialicons-regular.otf',
              ).readAsBytesSync(),
            ),
          ),
        );
      await tester.runAsync(() => icons.load());
      final repo = UiEvidenceRepository(scene.startsWith('p2') ? 'p2' : 'p1');
      final Widget screen = scene == 'overview'
          ? ClinicianCaseScreen(caseId: 'evidence-case', repository: repo)
          : scene == 'investigations'
          ? InvestigationsScreen(
              repository: repo,
              investigations: repo.investigations,
            )
          : RecommendationReviewScreen(
              caseId: 'evidence-case',
              repository: repo,
            );
      final key = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key,
          child: MaterialApp(
            theme: ThemeData(
              useMaterial3: true,
              fontFamily: 'EvidenceFont',
              colorSchemeSeed: Colors.teal,
            ),
            home: screen,
          ),
        ),
      );
      await tester.pumpAndSettle();
      expect(tester.takeException(), isNull);
      final dir = Platform.environment['SONGYI_UI_EVIDENCE_DIR'];
      if (dir != null) {
        final phase =
            Platform.environment['SONGYI_UI_EVIDENCE_PHASE'] ?? 'after';
        final boundary =
            key.currentContext!.findRenderObject()! as RenderRepaintBoundary;
        final image = (await tester.runAsync(
          () => boundary.toImage(pixelRatio: 1),
        ))!;
        final png = await tester.runAsync(
          () => image.toByteData(format: ui.ImageByteFormat.png),
        );
        await tester.runAsync(() async {
          await Directory(dir).create(recursive: true);
          await File(
            '$dir/$phase-$scene.png',
          ).writeAsBytes(png!.buffer.asUint8List());
        });
        image.dispose();
      }
    });
  }
}
