// Presentation metadata copied from the supplied db_pathway_integration rules.
const liveNodeLabels = <String, String>{
  'PATHWAY1:RENAL_DYSFUNCTION': 'What is the patient\'s eGFR value? (Unit: mL/min)',
  'PATHWAY1:ON_OSTEOPOROSIS_TREATMENT': 'Is the patient currently on osteoporosis treatment?',
  'PATHWAY1:RESIDENTIAL_OR_FRAILTY': 'Living situation, Frailty and Life expectancy (Please answer the following questions.)',
  'PATHWAY1:ADHERENCE_CONCERN': 'Is the patient able to adhere to their treatment plan? (Please answer the following questions.)',
  'PATHWAY1:DXA_SCAN_AVAILABILITY': 'Is the patient able to undergo a BMD DXA scan? (Select Yes if the patient has had a scan within prior 2 years)',
  'PATHWAY1:T_SCORE_CHECK': 'What are the patient\'s T-score for the femoral neck, hip, and lumbar spine?',
  'PATHWAY1:RECENT_MAJOR_FRACTURES': 'Has the patient had a hip fracture, vertebral fracture, or fractures at 2 or more sites in last 24 months?',
  'PATHWAY1:HIGH_RISK_CHECK': 'Is the patient at very high risk? (Please answer the following questions.)',
  'PATHWAY1:LEAF_RENAL_REFERRAL': 'Renal referral',
  'PATHWAY1:LEAF_REDIRECT_PATHWAY2': 'Redirect pathway2',
  'PATHWAY1:LEAF_DENOSUMAB_GP': 'Denosumab gp',
  'PATHWAY1:LEAF_ZOLEDRONIC_OR_RISEDRONATE_GP': 'Zoledronic or risedronate gp',
  'PATHWAY1:LEAF_ZOLEDRONIC_OR_RISEDRONATE_OR_DENOSUMAB_GP': 'Zoledronic or risedronate or denosumab gp',
  'PATHWAY1:LEAF_OSTEOANABOLIC_REFERRAL': 'Osteoanabolic referral',
  'PATHWAY1:LEAF_PRIVATELY_FUNDED_OSTEOANABOLIC_REFERRAL': 'Privately funded osteoanabolic referral',
  'PATHWAY2:ON_ANTIRESORPTIVE_TREATMENT': 'Is the patient currently on antiresorptive treatment?',
  'PATHWAY2:ANTIRESORPTIVE_TREATMENT_DURATION': 'Has the patient been receiving their pre-existing antiresorptive treatment for 12 months or longer?',
  'PATHWAY2:TREATMENT_ADHERENCE': 'Has the patient adhered to the treatment plan?',
  'PATHWAY2:SYMPTOMATIC_FRACTURE': 'Has the patient had 1 or more symptomatic fractures in last 12 months?',
  'PATHWAY2:MULTIPLE_FRACTURES': 'Has the patient had 2 or more fractures? (Check for occult vertebral fractures in previous chest or abdomen scan)',
  'PATHWAY2:CHECK_BMD': 'Does the patient have a BMD T-score below -3.0 at any site?',
  'PATHWAY2:MI_OR_STROKE_HISTORY': 'Does the patient have a history of myocardial infarction(MI) or stroke?',
  'PATHWAY2:SEQUENCING_WITH_HISTORY': 'Is the patient transitioning from denosumab?',
  'PATHWAY2:SEQUENCING_NO_HISTORY': 'Is the patient transitioning from denosumab?',
  'PATHWAY2:LEAF_REDIRECT_PATHWAY1': 'Redirect pathway1',
  'PATHWAY2:LEAF_STANDARD_ANTIRESORPTIVE_OPTIONS': 'Standard antiresorptive options',
  'PATHWAY2:LEAF_COMBINATION_THERAPY_REFERRAL': 'Combination therapy referral',
  'PATHWAY2:LEAF_TERIPARATIDE_REFERRAL': 'Teriparatide referral',
  'PATHWAY2:LEAF_RESTARTING_DENOSUMAB_REFERRAL': 'Restarting denosumab referral',
  'PATHWAY2:LEAF_ROMOSOZUMAB_REFERRAL': 'Romosozumab referral',
};

const liveNodeConditions = <String, String>{
  'PATHWAY1:RENAL_DYSFUNCTION': 'eGFR > 30',
  'PATHWAY1:ON_OSTEOPOROSIS_TREATMENT': 'Currently on osteoporosis treatment = Yes',
  'PATHWAY1:RESIDENTIAL_OR_FRAILTY': '(Lives in residential care = Yes OR Clinical Frailty Scale score >= 6 OR Life expectancy < 7)',
  'PATHWAY1:ADHERENCE_CONCERN': '(Known poor medication adherence = Yes OR Cognitive impairment affecting adherence = Yes)',
  'PATHWAY1:DXA_SCAN_AVAILABILITY': 'BMD DXA available or completed within two years = Yes',
  'PATHWAY1:T_SCORE_CHECK': '(Femoral neck T-score <= -2.5 OR Hip T-score <= -2.5 OR Lumbar spine T-score <= -2.5)',
  'PATHWAY1:RECENT_MAJOR_FRACTURES': 'Hip, vertebral, or multiple fractures in the last 24 months = Yes',
  'PATHWAY1:HIGH_RISK_CHECK': '((Femoral neck T-score <= -3.0 OR Hip T-score <= -3.0 OR Lumbar spine T-score <= -3.0) AND (Recent fracture within two years = Yes OR History of two or more fractures = Yes OR Additional clinical risk factors = Yes OR FRAX 10-year major osteoporotic fracture risk >= 30 OR FRAX 10-year hip fracture risk >= 4.5))',
  'PATHWAY2:ON_ANTIRESORPTIVE_TREATMENT': 'Currently on antiresorptive treatment = Yes',
  'PATHWAY2:ANTIRESORPTIVE_TREATMENT_DURATION': 'Antiresorptive treatment for 12 months or longer = Yes',
  'PATHWAY2:TREATMENT_ADHERENCE': 'Adhered to the treatment plan = Yes',
  'PATHWAY2:SYMPTOMATIC_FRACTURE': 'Symptomatic fracture in the last 12 months = Yes',
  'PATHWAY2:MULTIPLE_FRACTURES': 'Two or more fractures = Yes',
  'PATHWAY2:CHECK_BMD': 'BMD T-score below -3.0 at any site = Yes',
  'PATHWAY2:MI_OR_STROKE_HISTORY': 'History of myocardial infarction or stroke = Yes',
  'PATHWAY2:SEQUENCING_WITH_HISTORY': 'Sequencing from denosumab = Yes',
  'PATHWAY2:SEQUENCING_NO_HISTORY': 'Sequencing from denosumab = Yes',
};

